#!/usr/bin/env bash

usage="get_asset_pkg [kubernetes_version] [kubernetes_api] [cluster_name] [bucket]"

if [ "$1" == "" ]; then
    echo "$usage"
    exit 1
fi

if [ "$2" == "" ]; then
    echo "$usage"
    exit 1
fi

if [ "$3" == "" ]; then
    echo "$usage"
    exit 1
fi

if [ "$4" == "" ]; then
    echo "$usage"
    exit 1
fi

kubernetes_version=$1
kubernetes_api="$2"
cluster_name="$3"
bucket_path="$4"

scripts/gen_certs ${kubernetes_api} ${cluster_name} ${bucket_path}
scripts/get_binaries ${kubernetes_version} ${bucket_path}

rm -rf certs/secrets
