#!/usr/bin/env bash

usage="gen_binaries [version] [bucket]"

if [ "$1" == "" ]; then
    echo "$usage"
    exit 1
fi

if [ "$2" == "" ]; then
    echo "$usage"
    exit 1
fi

version=$1
bucket_path=$2

mkdir -p binaries/${version}

for binary in "kubelet"; do
    curl -o binaries/${version}/${binary} https://storage.googleapis.com/kubernetes-release/release/${version}/bin/linux/amd64/${binary}
    echo -n "sha512-$( shasum -a 512 binaries/${version}/${binary} | awk '{print $1}' )" > binaries/${version}/${binary}.checksum.txt
done

aws s3 cp --recursive binaries/ s3://${bucket_path}/binaries/
